apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb:8086
    user:
    password:
    database:
    basicAuth: false
    isDefault: true
    jsonData:
      httpMode: POST
      version: Flux
      organization: pcp-org
      defaultBucket: pcp-metrics
      tlsSkipVerify: true
    secureJsonData:
      token: pcp-admin-token-12345
    version: 1
    editable: true
